language: android

android:
  components:
    - tools
    - platform-tools
    - build-tools-25.0.2
    - support-repository
    - android-25
    - extra

jdk:
  - oraclejdk8

script:
  - chmod +x gradlew
  - ./gradlew clean build

cache:
  directories:
    - $HOME/.gradle